### ISSUE TITLE
Add BillBeeOrderId to OrderShipment

### ISSUE THREAD

**Issue by amahdavy** [billbeeio/billbee-csharp-sdk#26]
OrderID in OrderShipment.cs must be string same API and we need a new field on  OrderShipment.cs
Also need to change  AddShipment  :

public void AddShipment(OrderShipment shipment)
        {
             
            post($"/orders/{shipment.**BillBeeOrderId**}/shipment", shipment);
        }

**Comment by BenjaminAtBillbee** [comment]
If you pass OrderId, billbee finds the correct order and attaches the shipment to that order.
No need to add a BillBeeOrderId here.
