### ISSUE TITLE
Hello Api Newtonsoft.Json, Version=13.0.0.0 error

### ISSUE THREAD

**Issue by AbdulkadirTuncay** [billbeeio/billbee-csharp-sdk#42]
Hello,
I am using your billbee api on behalf of your user info@hafsa.de.
I was using your version 2.0.0 because your version 2.0.1 was wrong, but there were deficiencies in your order model and I could not get the result I wanted. You have released version 2.1.0 a few days ago, I am getting Newtonsoft.Json, Version=13.0.0.0 error on it.
Newtonsoft.Json Version=13.0.0.0 does not exist, there is version 13.0.1 however we are having problems in our nop.commerce project. I'm waiting for your help

**Comment by BenjaminAtBillbee** [comment]
With Release 2.1.0 we provide the Billbee.Api.Client.dll as .net standard, not as .net framework anymore.
This enables users to use it on existing .net framework projects as well as new .net core / .net 5 / .net 6 projects.

Version 2.1.0 in fact references Newtonsoft.Json in nuget-package Version 13.0.1 as you can see here:
https://github.com/billbeeio/billbee-csharp-sdk/blob/v2.1.0.0/Billbee.Api.Client/Billbee.Api.Client.csproj

Now, Newtonsoft.Json in nuget-package Version 13.0.1 contains a dll which has file-version 13.0.1, too, but it has an AssemblyVersion of 13.0.0.0 (which you can see with dotPeek for example). This is an inconsistency in the Newtonsoft.Json nuget-package, but should be no problem here. If you refer to nuget-package-version 13.0.1 it should work.

We tested the new version 2.1.0 with a .net framework project and there was no problem.

You could try the following:
- make sure that your 
- clean all bin/obj folders in your project
- do a nuget-restore
- rebuild your solution

You can find a working solution attached.
[BillbeeApiTestClient.zip](https://github.com/billbeeio/billbee-csharp-sdk/files/7717585/BillbeeApiTestClient.zip)
