### ISSUE TITLE
Missing CustomerAddresses Endpoint

### ISSUE THREAD

**Issue by mabru47** [billbeeio/billbee-csharp-sdk#56]
We would like to change the shipping address, but the current client has no way to do this. 
Is there a plan to support the /CustomerAddresses endpoint?

If there is no plan yet, I would make a custom build and provide the code. 
Is the  /CustomerAddresses endpoint final and ready for production?

https://app.billbee.io//swagger/ui/index#/CustomerAddresses

**Comment by BenjaminAtBillbee** [comment]
Thanks for the hint. We identified some more api-endpoints which are not yet implemented in the C#-sdk.
We plan to implement those endpoints in the C#-sdk in near future.
Yes, the /CustomerAddresses endpoint is ready - as mentioned, we will include it soon in the C#-sdk, too.

**Comment by BenjaminAtBillbee** [comment]
We created an own issue for all endpoints, which are not implemented yet in the C#-sdk (including the CustomerAddress Endpoint): #57 
Therefore closed this issue (duplicate).
