### ISSUE TITLE
Implement missing Api-Endpoints/methods

### ISSUE THREAD

**Issue by BenjaminAtBillbee** [billbeeio/billbee-csharp-sdk#57]
The following Api-Endpoints/methods are not yet implemented in the C#-SDK and should be added:
/api/v1/products/{id}:Delete
/api/v1/products:Post
/api/v1/products/category:Get
/api/v1/customers/{id}/addresses:Post
/api/v1/customers/addresses/{id}:Get
/api/v1/customers/addresses/{id}:Put
/api/v1/customers/addresses/{id}:Patch
/api/v1/customer-addresses:Get
/api/v1/customer-addresses:Post
/api/v1/customer-addresses/{id}:Get
/api/v1/customer-addresses/{id}:Put
/api/v1/enums/paymenttypes:Get
/api/v1/enums/shippingcarriers:Get
/api/v1/enums/shipmenttypes:Get
/api/v1/enums/orderstates:Get
/api/v1/layouts:Get
/api/v1/orders/{id}/parse-placeholders:Post
/api/v1/shipment/shipwithlabel:Post
/api/v1/shipment/shipments:Get

**Comment by mabru47** [comment]
Hey Benjamin,
i have just created a pull request as draft. If you have time, feel free to take a look. The endpoint and integration test were added. There are still a few things to do.  I hope it is helpful!
