### ISSUE TITLE
ShipmentWithLabel is calling wrong endpoint

### ISSUE THREAD

**Issue by mabru47** [billbeeio/billbee-csharp-sdk#59]
The ShipmentWithLabel()-Method is calling a wrong endpoint.
Wrong: /shipment/shipment
Correct: /shipment/shipwithlabel

[ShipmentEndPoint.cs](https://github.com/billbeeio/billbee-csharp-sdk/blob/master/Billbee.Api.Client/Endpoint/ShipmentEndPoint.cs)

I already have a custom build of the SDK and could provide later the necessary changes.

**Comment by BenjaminAtBillbee** [comment]
Thanks for the fix, I will merge your PR.
