### ISSUE TITLE
ChangeOrderState gibt NotFound zurück

### ISSUE THREAD

**Issue by wsuschetz** [billbeeio/billbee-csharp-sdk#83]
Hallo,
beim Aufruf von client.Orders.ChangeOrderState((long)BillBeeOrderID, OrderStateEnum.Im_Fulfillment);
erhalte ich leider "HTTP Response: NotFound: -" zurück
unabhängig vom vorhergehenden OrderState (Bestätigt oder Bezahlt), das betrifft auch ein Wechsel von Im_Fulfillment auf Versendet. 
Aber es betrifft nicht alle Bestellungen.

Vielen Dank für Eure Hilfe vorab!

**Comment by BenjaminAtBillbee** [comment]
Endpoint works as excpected.
Bitte sicherstellen, dass die richtige BillBeeOrderID reingegeben wird. Wenn eine ID angegeben wird zu der bei Billbee keine Order gefunden werden kann, liefert der Endpoint 404 zurück.
